version: 2

models:
  - name: salary_by_department
    columns:
      - name: department_name
        tests:
          - unique
          - not_null
  - name: employee_dependents
    columns:
      - name: employee_id
        tests:
          - unique
          - not_null
