name: "dbt_demo"
version: "0.1.0"
config-version: 2

profile: "dbt_demo"

source-paths: ["models"]
test-paths: ["tests"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
    - "target"
    - "dbt_modules"
